name: stocks
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  intl: ^0.19.0
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/


